version: '3.3'

services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        env_file:
            - .env
        restart: on-failure
        expose:
            - 3306
        networks:
            - wp-ntw 
        volumes:
            - mariadb-volume:/var/lib/mysql
        restart: always
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        env_file:
            - .env
        expose:
            - 9000
        restart: on-failure
        networks:
            - wp-ntw 
        volumes:
            - wordpress-volume:/var/www/html 
            - ./requirements/wordpress/files/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
        depends_on:
            - mariadb
        restart: always
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        env_file:
            - .env
        ports:
            - 443:443
        restart: on-failure
        networks:
            - wp-ntw 
        volumes:
            - wordpress-volume:/var/www/html 
        depends_on:
            - wordpress 
        restart: always
volumes:
    wordpress-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/bbeltran/data/wordpress-volume
    mariadb-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/bbeltran/data/mariadb-volume
networks:
    wp-ntw:
