version: '3.3'

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        env_file:
            - ./.env
        ports:
            - 443:443
        restart: on-failure
        networks:
            - wp-ntw 
        volumes:
            - wordpress-volume:/var/www/html 
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        env_file:
            - ./.env
        expose:
            - 9000
        restart: on-failure
        networks:
            - wp-ntw 
        volumes:
            - wordpress-volume:/var/www/html 
        depends_on:
            - mariadb
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        env_file:
            - ./.env
        restart: on-failure
        expose:
            - 3306
        networks:
            - wp-ntw 
        volumes:
            - mariadb-volume:/var/lib/mysql
volumes:
    wordpress-volume:
    mariadb-volume:
networks:
    wp-ntw:
        external:
            name: wp-ntw

