version: '3.3'

services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        env_file:
            - ./.env
        restart: on-failure
        expose:
            - 3306
        networks:
            - wp-ntw 
        volumes:
            - mariadb-volume:/var/lib/mysql
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        env_file:
            - ./.env
        expose:
            - 9000
        restart: on-failure
        networks:
            - wp-ntw 
        volumes:
            - wordpress-volume:/var/www/html 
            - ./requirements/wordpress/files/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
        depends_on:
            - mariadb
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        env_file:
            - ./.env
        ports:
            - 443:443
        restart: on-failure
        networks:
            - wp-ntw 
        volumes:
            - wordpress-volume:/var/www/html 
        depends_on:
            - wordpress 
volumes:
    wordpress-volume:
    mariadb-volume:
networks:
    wp-ntw:
